name: UPUK
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - ld_impl_linux-64=2.38
  - libedit=3.1.20221030
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1v
  - pip=23.2.1
  - python=3.9.0
  - python_abi=3.9
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.33.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - arrow==1.2.3
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - blessed==1.20.0
    - boto3==1.28.33
    - botocore==1.31.33
    - bravado==11.0.3
    - bravado-core==6.1.0
    - cachetools==5.3.1
    - charset-normalizer==3.2.0
    - click==8.1.7
    - contourpy==1.2.0
    - cycler==0.11.0
    - decorator==5.1.1
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fonttools==4.42.1
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - gpustat==1.1.1
    - grpcio==1.57.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - ipython==8.17.2
    - isoduration==20.11.0
    - jedi==0.19.1
    - jmespath==1.0.1
    - joblib==1.1.0
    - jsonpointer==2.4
    - jsonref==1.1.0
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - kiwisolver==1.4.5
    - kmeans-pytorch==0.3
    - llvmlite==0.40.1
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.8.1
    - matplotlib-inline==0.1.6
    - monotonic==1.6
    - msgpack==1.0.5
    - multidict==6.0.4
    - neptune-client==0.16.1
    - numba==0.57.1
    - numpy==1.22.4
    - nvidia-ml-py==12.535.108
    - oauthlib==3.2.2
    - packaging==23.1
    - pandas==1.4.1
    - parso==0.8.3
    - pexpect==4.8.0
    - pillow==9.0.1
    - prompt-toolkit==3.0.39
    - protobuf==4.24.1
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pygments==2.16.1
    - pyjwt==2.8.0
    - pynndescent==0.5.10
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.2.10
    - pytz==2023.3
    - pyyaml==6.0.1
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3987==1.3.8
    - rpds-py==0.9.2
    - rsa==4.9
    - s3transfer==0.6.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - simplejson==3.19.1
    - six==1.16.0
    - smmap==5.0.0
    - stack-data==0.6.3
    - swagger-spec-validator==3.0.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - threadpoolctl==3.2.0
    - torch==1.11.0
    - torchmetrics==0.2.0
    - torchvision==0.12.0
    - tqdm==4.63.0
    - traitlets==5.13.0
    - typing-extensions==4.7.1
    - umap==0.1.1
    - umap-learn==0.5.2
    - uri-template==1.3.0
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - webcolors==1.13
    - websocket-client==1.6.2
    - werkzeug==2.3.7
    - yarl==1.9.2
    - zipp==3.16.2
